### ISSUE TITLE
Need updated for new .net 9 update

### ISSUE THREAD

**Issue by SlyTheFloof** [shadowpanther/resonite-headless#12]
Need updated for new .net 9 update

**Comment by shadowpanther** [comment]
Ah, looks like I still had the old Headless install on the permanent volume. Hold on, testing with the newer Ubuntu release.

**Comment by shadowpanther** [comment]
Should be fixed by https://github.com/shadowpanther/resonite-headless/commit/b37130b628a125124c4e339f1f49ec21c463a566
Docker Hub image is currently building, should take a couple of minutes.
