### ISSUE TITLE
Feature request: Toggleable IPv6 mod

### ISSUE THREAD

**Issue by archer007** [shadowpanther/resonite-headless#9]
Can you add https://github.com/bontebok/ResoniteIPv6Mod/tree/main so that IPv6-only clients with the mod or just people who want to use the mod can connect over IPv6?

**Comment by bontebok** [comment]
@archer007 Hmm, I never thought about including the IPv6 Mod install as part of the headless docker I maintain since it's as simple as enabling RML and dropping just the IPv6 mod into the rml_mods files.

Curious, why would you want it included as opposed to dropping in the mod and having it work that way?

**Comment by bontebok** [comment]
Thinking this through further, I'd actually recommend against doing this. By default, Docker's IPv6 support is disabled by default and must be enabled at the daemon level in order for the container to use IPv6. If IPv6 is not present in Resonite when the Mod loads, it will definitely fail and cause startup and connection problems.

I would recommend tackle this another way, with external scripts or a custom cloud-init to configure the docker daemon and pull down the IPv6 Mod and place that into the rml_mods directory.

**Comment by shadowpanther** [comment]
> Can you add https://github.com/bontebok/ResoniteIPv6Mod/tree/main so that IPv6-only clients with the mod or just people who want to use the mod can connect over IPv6?

I don't know how to work with mods, and I prefer to keep this image as vanilla as it gets. If someone else is willing to maintain a fork with mod support and IPV6 mod included, they absolutely can.
